# Generated by Django 5.1.6 on 2025-02-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
    ]
